services:
  wordpress:
    image: wordpress:latest
    container_name: dockerwp-wp
    restart: always
    ports:
      - "9001:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: dockerwp
      WORDPRESS_DB_PASSWORD: dockerwp_password
      WORDPRESS_DB_NAME: dockerwp_db
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - dockerwp_network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: dockerwp-mysql
    restart: always
    environment:
      MYSQL_DATABASE: dockerwp_db
      MYSQL_USER: dockerwp
      MYSQL_PASSWORD: dockerwp_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - dockerwp_network

  phpmyadmin_dockerwp:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_dockerwp
    restart: always
    ports:
      - "9002:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    networks:
      - dockerwp_network
    depends_on:
      - db

volumes:
  db_data:

networks:
  dockerwp_network:
    driver: bridge